apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: path-normalization-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: path-normalization.example.com
    http:
      paths:
        - path: "/ip"
          pathType: Exact
          backend:
            service:
              name: httpbin
              port:
                number: 8000
